#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates" / "godot_addon"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def copy_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(src)
    shutil.copytree(src, dst, dirs_exist_ok=True)


def write_preview_project_files(out_dir: Path, song_id: str, preview_difficulty: str) -> None:
    project_godot = f'''; Engine configuration file.
; Generated by audio-to-rhythm-godot-kit Godot addon exporter.

config_version=5

[application]

config/name="rhythmkit_{song_id}"
run/main_scene="res://scenes/RhythmKitPreview.tscn"
config/features=PackedStringArray("4.6")

[display]

window/size/viewport_width=900
window/size/viewport_height=1400
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[rendering]

renderer/rendering_method="gl_compatibility"
'''
    write_text(out_dir / "project.godot", project_godot)
    preview_scene = f'''[gd_scene load_steps=2 format=3]

[ext_resource type="PackedScene" path="res://addons/rhythmkit/RhythmGameView.tscn" id="1"]

[node name="RhythmKitPreview" instance=ExtResource("1")]
bundle_path = "res://levels/{song_id}"
difficulty = "{preview_difficulty}"
auto_start = true
'''
    write_text(out_dir / "scenes" / "RhythmKitPreview.tscn", preview_scene)


def export_godot_addon_package(bundle_dir: str | Path, out_dir: str | Path, *, song_id: str | None = None, preview_difficulty: str = "normal") -> dict:
    bundle_dir = Path(bundle_dir).resolve()
    out_dir = Path(out_dir).resolve()
    metadata_path = bundle_dir / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(f"Bundle metadata not found: {metadata_path}")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    song_id = song_id or str(metadata.get("song_id", bundle_dir.name))

    copy_tree(TEMPLATE_DIR / "addons", out_dir / "addons")
    copy_tree(bundle_dir, out_dir / "levels" / song_id)
    write_preview_project_files(out_dir, song_id, preview_difficulty)

    readme = f"""# Godot RhythmKit Import Package

This folder can be opened as a preview Godot project, or copied into an existing Godot project.

## Preview

Open this folder with Godot 4.6+ and run:

```text
project.godot
```

Preview scene:

```text
res://scenes/RhythmKitPreview.tscn
```

## Import into an existing Godot project

Copy these folders into the target project:

```text
addons/rhythmkit/
levels/{song_id}/
```

Then instantiate:

```gdscript
var view = preload("res://addons/rhythmkit/RhythmGameView.tscn").instantiate()
add_child(view)
view.load_bundle("res://levels/{song_id}", "{preview_difficulty}")
view.start_game()
```

For AI-assisted integration, use:

```text
levels/{song_id}/integration/AI_GODOT_IMPORT_PROMPT.md
```
"""
    write_text(out_dir / "README_GODOT_IMPORT.md", readme)
    manifest = {
        "godot_addon_package": str(out_dir),
        "addon": str(out_dir / "addons" / "rhythmkit"),
        "level": str(out_dir / "levels" / song_id),
        "preview_scene": "res://scenes/RhythmKitPreview.tscn",
        "preview_difficulty": preview_difficulty,
    }
    write_text(out_dir / "godot_addon_manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2))
    return manifest


def main() -> int:
    ap = argparse.ArgumentParser(description="Export a rhythm bundle as a Godot addon/import package")
    ap.add_argument("bundle")
    ap.add_argument("--out", required=True)
    ap.add_argument("--song-id", default=None)
    ap.add_argument("--preview-difficulty", default="normal")
    args = ap.parse_args()
    manifest = export_godot_addon_package(args.bundle, args.out, song_id=args.song_id, preview_difficulty=args.preview_difficulty)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
