#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates" / "godot_addon"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def copy_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(src)
    shutil.copytree(src, dst, dirs_exist_ok=True)


def write_configured_runtime_scene(out_dir: Path, song_id: str, preview_difficulty: str) -> None:
    scene_path = out_dir / "addons" / "rhythmkit" / "RhythmGameView.tscn"
    if not scene_path.exists():
        return
    text = scene_path.read_text(encoding="utf-8")
    if "bundle_path = " not in text:
        text = text.replace(
            'script = ExtResource("1")\n',
            'script = ExtResource("1")\n'
            f'bundle_path = "res://levels/{song_id}"\n'
            f'difficulty = "{preview_difficulty}"\n'
            'auto_start = true\n',
        )
        scene_path.write_text(text, encoding="utf-8")


def write_preview_project_files(out_dir: Path, song_id: str, preview_difficulty: str) -> None:
    project_godot = f'''; Engine configuration file.
; Generated by audio-to-rhythm-godot-kit Godot addon exporter.

config_version=5

[application]

config/name="rhythmkit_{song_id}"
run/main_scene="res://scenes/RhythmKitPreview.tscn"
config/features=PackedStringArray("4.6")

[display]

window/size/viewport_width=900
window/size/viewport_height=1400
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[rendering]

renderer/rendering_method="gl_compatibility"
'''
    write_text(out_dir / "project.godot", project_godot)
    preview_scene = f'''[gd_scene load_steps=2 format=3]

[ext_resource type="PackedScene" path="res://addons/rhythmkit/RhythmGameView.tscn" id="1"]

[node name="RhythmKitPreview" instance=ExtResource("1")]
bundle_path = "res://levels/{song_id}"
difficulty = "{preview_difficulty}"
auto_start = true
'''
    write_text(out_dir / "scenes" / "RhythmKitPreview.tscn", preview_scene)


def export_godot_addon_package(bundle_dir: str | Path, out_dir: str | Path, *, song_id: str | None = None, preview_difficulty: str = "normal") -> dict:
    bundle_dir = Path(bundle_dir).resolve()
    out_dir = Path(out_dir).resolve()
    metadata_path = bundle_dir / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(f"Bundle metadata not found: {metadata_path}")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    song_id = song_id or str(metadata.get("song_id", bundle_dir.name))

    copy_tree(TEMPLATE_DIR / "addons", out_dir / "addons")
    copy_tree(bundle_dir, out_dir / "levels" / song_id)
    write_configured_runtime_scene(out_dir, song_id, preview_difficulty)
    write_preview_project_files(out_dir, song_id, preview_difficulty)

    readme = f"""# Godot RhythmKit Import Package

This folder is designed for AI-assisted import into an existing Godot game.

It can also be opened directly as a preview Godot project.

## Preview first

Open this folder with Godot 4.6+ and run:

```text
project.godot
```

Preview scene:

```text
res://scenes/RhythmKitPreview.tscn
```

## AI-first import into the user's game

Give Codex / Claude Code / Cursor / Hermes access to the user's Godot project and paste:

```text
levels/{song_id}/integration/AI_GODOT_IMPORT_PROMPT.md
```

Tell the AI where the rhythm level should appear: main menu, level select, NPC, map trigger, or debug entry.

The AI should copy these folders into the target Godot project:

```text
addons/rhythmkit/        # reusable runtime, usually installed once
levels/{song_id}/        # this song's bundle
```

Then it should wire the user's chosen entry point to:

```gdscript
var view = preload("res://addons/rhythmkit/RhythmGameView.tscn").instantiate()
add_child(view)
view.load_bundle("res://levels/{song_id}", "{preview_difficulty}")
view.start_game()
```

## Adding more songs later

After `addons/rhythmkit/` is installed once, future songs only need another bundle under:

```text
levels/<new_song_id>/
```

Ask the AI to generate/copy the new bundle, update the same menu/level-select/trigger integration, and run Godot verification.
"""
    write_text(out_dir / "README_GODOT_IMPORT.md", readme)
    manifest = {
        "godot_addon_package": str(out_dir),
        "addon": str(out_dir / "addons" / "rhythmkit"),
        "level": str(out_dir / "levels" / song_id),
        "preview_scene": "res://scenes/RhythmKitPreview.tscn",
        "preview_difficulty": preview_difficulty,
    }
    write_text(out_dir / "godot_addon_manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2))
    return manifest


def main() -> int:
    ap = argparse.ArgumentParser(description="Export a rhythm bundle as a Godot addon/import package")
    ap.add_argument("bundle")
    ap.add_argument("--out", required=True)
    ap.add_argument("--song-id", default=None)
    ap.add_argument("--preview-difficulty", default="normal")
    args = ap.parse_args()
    manifest = export_godot_addon_package(args.bundle, args.out, song_id=args.song_id, preview_difficulty=args.preview_difficulty)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
